package config

import "time"

const (
	ItemsPerPage               = 20
	LIGHT_MAX_NEW_SPOTS  int64 = 2
	MEDIUM_MAX_NEW_SPOTS int64 = 5
	HEAVY_MAX_NEW_SPOTS  int64 = 10

	LIGHT_MAX_INFREQUENT_SPOTS  = 7
	MEDIUM_MAX_INFREQUENT_SPOTS = 14
	HEAVY_MAX_INFREQUENT_SPOTS  = 20

	LIGHT_MAX_INTERLEAVE_SPOTS  = 10
	MEDIUM_MAX_INTERLEAVE_SPOTS = 12
	HEAVY_MAX_INTERLEAVE_SPOTS  = 20

	RESUME_PLAN_TIME_LIMIT = 12 * time.Hour
	INFREQUENT_SPOT_OFFSET = 12 * time.Hour

	MAX_ALLOWED_RANDOM_SPOTS = 20
	MAX_UPLOAD_SIZE          = 1024 * 1024 // 1MiB
)
