// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type Credential struct {
	CredentialID    []byte `json:"credentialId"`
	PublicKey       []byte `json:"publicKey"`
	Transport       []byte `json:"transport"`
	AttestationType string `json:"attestationType"`
	Flags           []byte `json:"flags"`
	Authenticator   []byte `json:"authenticator"`
	UserID          string `json:"userId"`
}

type Piece struct {
	ID              string         `json:"id"`
	Title           string         `json:"title"`
	Description     sql.NullString `json:"description"`
	Composer        sql.NullString `json:"composer"`
	Measures        sql.NullInt64  `json:"measures"`
	BeatsPerMeasure sql.NullInt64  `json:"beatsPerMeasure"`
	GoalTempo       sql.NullInt64  `json:"goalTempo"`
	UserID          string         `json:"userId"`
	LastPracticed   sql.NullInt64  `json:"lastPracticed"`
	Stage           string         `json:"stage"`
	KeyID           sql.NullInt64  `json:"keyId"`
	ModeID          sql.NullInt64  `json:"modeId"`
}

type PracticePlan struct {
	ID            string         `json:"id"`
	UserID        string         `json:"userId"`
	Intensity     string         `json:"intensity"`
	Date          int64          `json:"date"`
	Completed     bool           `json:"completed"`
	PracticeNotes sql.NullString `json:"practiceNotes"`
	LastPracticed sql.NullInt64  `json:"lastPracticed"`
}

type PracticePlanPiece struct {
	PracticePlanID string `json:"practicePlanId"`
	PieceID        string `json:"pieceId"`
	PracticeType   string `json:"practiceType"`
	Completed      bool   `json:"completed"`
	Sessions       int64  `json:"sessions"`
	Idx            int64  `json:"idx"`
}

type PracticePlanReading struct {
	PracticePlanID string `json:"practicePlanId"`
	ReadingID      string `json:"readingId"`
	Completed      bool   `json:"completed"`
	Idx            int64  `json:"idx"`
}

type PracticePlanScale struct {
	PracticePlanID string `json:"practicePlanId"`
	UserScaleID    string `json:"userScaleId"`
	Completed      bool   `json:"completed"`
	Idx            int64  `json:"idx"`
}

type PracticePlanSpot struct {
	PracticePlanID string         `json:"practicePlanId"`
	SpotID         string         `json:"spotId"`
	PracticeType   string         `json:"practiceType"`
	Evaluation     sql.NullString `json:"evaluation"`
	Completed      bool           `json:"completed"`
	Idx            int64          `json:"idx"`
}

type Reading struct {
	ID        string         `json:"id"`
	Title     string         `json:"title"`
	Info      sql.NullString `json:"info"`
	Completed bool           `json:"completed"`
	Composer  sql.NullString `json:"composer"`
	UserID    string         `json:"userId"`
}

type Scale struct {
	ID     int64 `json:"id"`
	KeyID  int64 `json:"keyId"`
	ModeID int64 `json:"modeId"`
}

type ScaleKey struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Cof  int64  `json:"cof"`
}

type ScaleMode struct {
	ID    int64  `json:"id"`
	Name  string `json:"name"`
	Basic bool   `json:"basic"`
	Cof   int64  `json:"cof"`
}

type Section struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	PieceID     string `json:"pieceId"`
}

type Spot struct {
	ID             string         `json:"id"`
	PieceID        string         `json:"pieceId"`
	Name           string         `json:"name"`
	Stage          string         `json:"stage"`
	Measures       sql.NullString `json:"measures"`
	AudioPromptUrl string         `json:"audioPromptUrl"`
	ImagePromptUrl string         `json:"imagePromptUrl"`
	NotesPrompt    string         `json:"notesPrompt"`
	TextPrompt     string         `json:"textPrompt"`
	CurrentTempo   sql.NullInt64  `json:"currentTempo"`
	LastPracticed  sql.NullInt64  `json:"lastPracticed"`
	StageStarted   sql.NullInt64  `json:"stageStarted"`
	SkipDays       int64          `json:"skipDays"`
	Priority       int64          `json:"priority"`
	SectionID      sql.NullString `json:"sectionId"`
}

type SpotsSection struct {
	SpotID    string `json:"spotId"`
	SectionID string `json:"sectionId"`
	PieceID   string `json:"pieceId"`
}

type User struct {
	ID                         string         `json:"id"`
	Fullname                   string         `json:"fullname"`
	Email                      string         `json:"email"`
	EmailVerified              sql.NullBool   `json:"emailVerified"`
	ActivePracticePlanID       sql.NullString `json:"activePracticePlanId"`
	ActivePracticePlanStarted  sql.NullInt64  `json:"activePracticePlanStarted"`
	ConfigDefaultPlanIntensity string         `json:"configDefaultPlanIntensity"`
	ConfigTimeBetweenBreaks    int64          `json:"configTimeBetweenBreaks"`
}

type UserScale struct {
	ID            string        `json:"id"`
	UserID        string        `json:"userId"`
	ScaleID       int64         `json:"scaleId"`
	PracticeNotes string        `json:"practiceNotes"`
	LastPracticed sql.NullInt64 `json:"lastPracticed"`
	Reference     string        `json:"reference"`
	Working       bool          `json:"working"`
}
