// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"database/sql"
)

type Credential struct {
	CredentialID    []byte
	PublicKey       []byte
	Transport       []byte
	AttestationType string
	Flags           []byte
	Authenticator   []byte
	UserID          string
}

type User struct {
	ID            string
	Fullname      string
	Email         string
	EmailVerified sql.NullBool
}
