// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const clearActivePracticePlan = `-- name: ClearActivePracticePlan :exec
UPDATE users
SET active_practice_plan_id = NULL, active_practice_plan_started = NULL
WHERE id = ?1
`

func (q *Queries) ClearActivePracticePlan(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, clearActivePracticePlan, userID)
	return err
}

const countUserCredentials = `-- name: CountUserCredentials :one
SELECT COUNT(*) FROM credentials WHERE user_id = ?
`

func (q *Queries) CountUserCredentials(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserCredentials, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCredential = `-- name: CreateCredential :one
INSERT INTO credentials (
    credential_id,
    public_key,
    transport,
    attestation_type,
    flags,
    authenticator,
    user_id
) VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING credential_id, public_key, transport, attestation_type, flags, authenticator, user_id
`

type CreateCredentialParams struct {
	CredentialID    []byte `json:"credentialId"`
	PublicKey       []byte `json:"publicKey"`
	Transport       []byte `json:"transport"`
	AttestationType string `json:"attestationType"`
	Flags           []byte `json:"flags"`
	Authenticator   []byte `json:"authenticator"`
	UserID          string `json:"userId"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error) {
	row := q.db.QueryRowContext(ctx, createCredential,
		arg.CredentialID,
		arg.PublicKey,
		arg.Transport,
		arg.AttestationType,
		arg.Flags,
		arg.Authenticator,
		arg.UserID,
	)
	var i Credential
	err := row.Scan(
		&i.CredentialID,
		&i.PublicKey,
		&i.Transport,
		&i.AttestationType,
		&i.Flags,
		&i.Authenticator,
		&i.UserID,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, fullname, email) VALUES (?, ?, ?)
RETURNING id, fullname, email, email_verified, active_practice_plan_id, active_practice_plan_started
`

type CreateUserParams struct {
	ID       string `json:"id"`
	Fullname string `json:"fullname"`
	Email    string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.ID, arg.Fullname, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Email,
		&i.EmailVerified,
		&i.ActivePracticePlanID,
		&i.ActivePracticePlanStarted,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const deleteUserCredentials = `-- name: DeleteUserCredentials :exec
DELETE FROM credentials WHERE user_id = ?
`

func (q *Queries) DeleteUserCredentials(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserCredentials, userID)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, fullname, email, email_verified, active_practice_plan_id, active_practice_plan_started
FROM users
WHERE email = LOWER(?1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Email,
		&i.EmailVerified,
		&i.ActivePracticePlanID,
		&i.ActivePracticePlanStarted,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, fullname, email, email_verified, active_practice_plan_id, active_practice_plan_started
FROM users
WHERE id = ?1
`

func (q *Queries) GetUserByID(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Email,
		&i.EmailVerified,
		&i.ActivePracticePlanID,
		&i.ActivePracticePlanStarted,
	)
	return i, err
}

const getUserCredentials = `-- name: GetUserCredentials :many
SELECT credential_id, public_key, transport, attestation_type, flags, authenticator, user_id
FROM credentials
WHERE user_id = ?
`

func (q *Queries) GetUserCredentials(ctx context.Context, userID string) ([]Credential, error) {
	rows, err := q.db.QueryContext(ctx, getUserCredentials, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Credential
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.CredentialID,
			&i.PublicKey,
			&i.Transport,
			&i.AttestationType,
			&i.Flags,
			&i.Authenticator,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserForLogin = `-- name: GetUserForLogin :one
SELECT
    users.id,
    users.fullname,
    users.email,
    users.email_verified,
    COUNT(credentials.credential_id) AS credential_count
FROM users
LEFT JOIN credentials ON users.id = credentials.user_id
WHERE users.email = LOWER(?1)
`

type GetUserForLoginRow struct {
	ID              string       `json:"id"`
	Fullname        string       `json:"fullname"`
	Email           string       `json:"email"`
	EmailVerified   sql.NullBool `json:"emailVerified"`
	CredentialCount int64        `json:"credentialCount"`
}

func (q *Queries) GetUserForLogin(ctx context.Context, email string) (GetUserForLoginRow, error) {
	row := q.db.QueryRowContext(ctx, getUserForLogin, email)
	var i GetUserForLoginRow
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Email,
		&i.EmailVerified,
		&i.CredentialCount,
	)
	return i, err
}

const setActivePracticePlan = `-- name: SetActivePracticePlan :exec
UPDATE users
SET active_practice_plan_id = ?, active_practice_plan_started = unixepoch('now')
WHERE id = ?
`

type SetActivePracticePlanParams struct {
	ActivePracticePlanID sql.NullString `json:"activePracticePlanId"`
	UserID               string         `json:"userId"`
}

func (q *Queries) SetActivePracticePlan(ctx context.Context, arg SetActivePracticePlanParams) error {
	_, err := q.db.ExecContext(ctx, setActivePracticePlan, arg.ActivePracticePlanID, arg.UserID)
	return err
}

const setEmailVerified = `-- name: SetEmailVerified :exec
UPDATE users SET email_verified = 1 WHERE id = ?
RETURNING id, fullname, email, email_verified, active_practice_plan_id, active_practice_plan_started
`

func (q *Queries) SetEmailVerified(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, setEmailVerified, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET fullname = COALESCE(?, fullname),
    email = COALESCE(?, email),
    email_verified = COALESCE(?, email_verified)
WHERE id = ?
RETURNING id, fullname, email, email_verified, active_practice_plan_id, active_practice_plan_started
`

type UpdateUserParams struct {
	Fullname      string       `json:"fullname"`
	Email         string       `json:"email"`
	EmailVerified sql.NullBool `json:"emailVerified"`
	ID            string       `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Fullname,
		arg.Email,
		arg.EmailVerified,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Email,
		&i.EmailVerified,
		&i.ActivePracticePlanID,
		&i.ActivePracticePlanStarted,
	)
	return i, err
}
